apiVersion: apps/v1           
kind: Deployment              
metadata:
  name: chat-app           
  labels:                     
    app: chat-service
spec:
  replicas: 1                 
  selector:
    matchLabels:              
      app: chat-app
  template:                   
    metadata:
      labels:                 
        app: chat-app
    spec:                     
      containers:
      - name: chat-app
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

