apiVersion: v1                
kind: Service                 
metadata:                     
  name: chat-service       
  labels:                     
    app: chat-service       
spec:                         
  type: LoadBalancer              
  selector:
    app: chat-service      
  ports:                      
  - name: http
    port: 8080    