--- 
- name: kubernetes
  hosts: localhost
  become: yes
  vars:
    image_name: "nginx"
    container_name: "webserver"
    kubeconfig_path: "xyz"
  tasks:
    - name: Create a Service object from an inline definition
      kubernetes.core.k8s:
        # kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: chat-server
            labels:
              service: chat
          spec:
            selector:
              app: chat
            ports:
            - protocol: TCP
              targetPort: 8080
              name: http
              port: 8000
    - name: deployment
      kubernetes.core.k8s:
        # kubeconfig: "{{ kubeconfig_path }}"
        state: present
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: chat-app-deployment
          labels:
            app: chat
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: chat
          template:
            metadata:
              labels:
                app: chat
            spec:
              containers:
              - name: chat-app-container
                image: nginx:1.14.2
                ports:
                - containerPort: 80